- name: Download k3s installer script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: 0755

- name: Install k3s and init cluster
  shell: /tmp/k3s-install.sh --disable traefik --disable servicelb server --cluster-init
  environment:
    K3S_TOKEN: "{{ k3s_token }}"

- name: Delete installer script
  file:
    path: /tmp/k3s-install.sh
    state: absent

- name: Test K3S is up
  shell: k3s kubectl get nodes -o wide